### ISSUE TITLE
Build From Source With Docker import problem

### ISSUE THREAD

**Issue by liuhuiyu991026** [AndroidFlakyTest/FlakeScanner-tool#9]
您好，我在运行您的FlakeScanner源码时，执行bash scripts/build-docker.bash时，提示“object jdi is not a member of package com.sun”，后续由于jdi包没能成功引入，导致一系列依赖错误，请问这个应该怎么解决呢？谢谢！
![$TN2CAPF%%95TCMZBIVG9DF](https://user-images.githubusercontent.com/48245089/144845703-8421bea3-9924-494c-a1c5-ba8e35f0743d.png)
![`$THS)J(CKDEFUVA@18OR9R](https://user-images.githubusercontent.com/48245089/144845709-654b92a7-6f5b-457e-9453-6959f5426b2f.png)

**Comment by zhendong2050** [comment]
看下那行代码，是不是个拼写错误？

**Comment by aht360** [comment]
I'm having this same issue =/
